### ISSUE TITLE
The improved alias doesn't work

### ISSUE THREAD

**Issue by yellowiscool** [alexjc/neural-enhance#37]
Hei,

The improved alias fails to bind the folder correctly. The python script crashes with `No such file or directory: 'input/example.jpg'`.  I belive `$(pwd)` should be added somewhere before the `dirname` command.

Also, it's probably a good idea to add `--rm`  in the docker command, so the containers are automatically removed after completion.

**Comment by hemel-cse** [comment]
It works see here [https://github.com/alexjc/neural-enhance/issues/28](Issue28)

**Comment by yellowiscool** [comment]
Isn't it about the old alias. This one from the readme `alias enhance="function ne() { docker run -v \`dirname \$1\`:/ne/input -it alexjc/neural-enhance input/\`basename \$1\`; }; ne"` doesn't.

**Comment by crsrusl** [comment]
Can confirm alias does not work.

Mac OS X Sierra 10.12.1
Docker 1.12.1

**Comment by crsrusl** [comment]
This seems to work on my machine:

`alias enhance="function ne() { docker run -v ${PWD}:/ne/input -it alexjc/neural-enhance input/\`basename \$1\`; }; ne"`

**Comment by alexjc** [comment]
I think it should work now, both absolute paths and relative ones. Thanks for reporting and suggesting the fix!

**Comment by rudelm** [comment]
Hi,

I've tried the updated alias but it still seems to not find the images.

The image is in a subfolder of where I execute enhance, e.g. input/images/foto.jpg

Output from Docker:

`enhance images/foto.jpg
                             _              _
  _ __   ___ _   _ _ __ __ _| |   ___ _ __ | |__   __ _ _ __   ___ ___
 | '_ \ / _ \ | | | '__/ _` | |  / _ \ '_ \| '_ \ / _` | '_ \ / __/ _ \
 | | | |  __/ |_| | | | (_| | | |  __/ | | | | | | (_| | | | | (_|  __/
 |_| |_|\___|\__,_|_|  \__,_|_|  \___|_| |_|_| |_|\__,_|_| |_|\___\___|

Super Resolution for images and videos powered by Deep Learning!
  - Code licensed as AGPLv3, models under CC BY-NC-SA.
  - Using the device `cpu` for neural computation.

Enhancing 1 image(s) specified on the command-line.
  - Loaded file `ne4x-small-0.1.pkl.bz2` with trained model.

input/foto.jpg
Traceback (most recent call last):
  File "enhance.py", line 519, in <module>
    img = scipy.ndimage.imread(filename, mode='RGB')
  File "/opt/conda/lib/python3.5/site-packages/scipy/ndimage/io.py", line 24, in imread
    return _imread(fname, flatten, mode)
  File "/opt/conda/lib/python3.5/site-packages/scipy/misc/pilutil.py", line 154, in imread
    im = Image.open(name)
  File "/opt/conda/lib/python3.5/site-packages/PIL/Image.py", line 2282, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'input/foto.jpg'`

I've tested various other combinations with and without the input or images folder, but no chance.

Tested on Mac OS 10.12.1 with Docker 1.12.1

**Comment by magin** [comment]
Same problem, trying with the latest alias and it doesn't work.

**Comment by rudelm** [comment]
The updated alias still doesn't work:

`enhance images/image.jpg
-bash: -1: substring expression < 0`

Any chance this could be fixed?
